baseURL = 'https://eugo.uk/'
languageCode = 'en-us'
title = 'eugo travel'
theme = 'eugo-theme'
enableRobotsTXT = "true"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  canonicalUrl = 'https://eugo.uk/'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[markup.goldmark.renderer]
  unsafe = true 
